- name: Copy over Desktop file 
  copy: src=loudcheck dest=/usr/bin/loud-check

- name: Installing Basic Packages
  apt: pkg={{item}} state=installed
  with items: 
  - emacs
  - ssh
  - chromium-browser
  - slay 
  - htop
  - gparted
  - rdesktop
  - byobu
  - git 
  - ansible
  - virtualbox

