- name: Copy over Desktop file 
  copy: src=mshs-server.desktop dest=/usr/share/applications/mshs-server.desktop

- name: Move Script into place
  copy: src=mshs-server-connect dest=/usr/bin/mshs-server-connect

- name: Force Override on Unity Bar
  copy: src=10_local-unity-launcher.gschema.override dest=/usr/share/glib-2.0/schemas/10_local-unity-launcher.gschema.override

- name: Locally set Unity Launcher
  command: gsettings set com.canonical.Unity.Launcher favorites "['ubiquity-gtkui.desktop', 'nautilus-home.desktop', 'chromium-browser.desktop', 'firefox.desktop', 'gnome-terminal.desktop', mshs-server.desktop']"

- name: Recompile Schema
  command: glib-compile-schemas /usr/share/glib-2.0/schemas

- name: Installing Basic Packages
  apt: pkg={{item}} state=installed
  with items: 
  - emacs
  - ssh
  - chromium-browser
  - slay 
  - htop
  - gparted
  - rdesktop
